name: Build and Test Seal

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

      - name: Run tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          BIN_PATH="./target/release/seal"
          TEST_CMD="$BIN_PATH ./tests/run_tests.luau"
          STDERR_CHECK=$($TEST_CMD 2>&1 >/dev/null)
          if [ -n "$STDERR_CHECK" ]; then
            echo "Tests failed! STDERR contains output."
            exit 1
          fi
        shell: bash

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          $BIN_PATH = ".\target\release\seal.exe"
          $TEST_CMD = "$BIN_PATH .\tests\run_tests.luau"
          $STDERR_CHECK = & $TEST_CMD 2>&1 | Out-String
          if ($STDERR_CHECK -ne "") {
            Write-Host "Tests failed! STDERR contains output."
            exit 1
          }
        shell: pwsh

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: seal-build-${{ matrix.os }}
          path: ./target/release/seal*
